//
// ApiResponseOfListOfPageData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ApiResponseOfListOfPageData: SaaSposeResponse {

    public var model: [PageData]?

public enum CodingKeys: String, CodingKey { 
        case model = "Model"
    }

    public init(model: [PageData]?) {
        self.model = model
        super.init()
    }
    
    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(model, forKey: "Model")
        
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        model = try container.decodeIfPresent([PageData].self, forKey: "Model")
        
        try super.init(from: decoder)
    }


}

