//
// CreateNewResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateNewResponse: Codable {

    public var created: String?

public enum CodingKeys: String, CodingKey { 
        case created = "Created"
    }

    public init(created: String?) {
        self.created = created
    }


}

