//
// CreateNewResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class CreateNewResponse: SaaSposeResponse {

    public var created: String?

public enum CodingKeys: String, CodingKey { 
        case created = "Created"
    }

    public init(created: String?) {
        self.created = created
        super.init()
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(created, forKey: "Created")
        
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        created = try container.decodeIfPresent(String.self, forKey: "Created")
        
        try super.init(from: decoder)
    }

}

