//
// DiagramResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DiagramResponse: Codable {

    public var status: String?
    public var code: Int32
    public var diagramModel: DiagramModel?

public enum CodingKeys: String, CodingKey { 
        case status = "Status"
        case code = "Code"
        case diagramModel = "diagramModel"
    }

    public init(status: String?, code: Int32, diagramModel: DiagramModel?) {
        self.status = status
        self.code = code
        self.diagramModel = diagramModel
    }


}

