//
// DiagramSaveOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class DiagramSaveOptions: SaveOptionsModel {

    public var autoFitPageToDrawingContent: Bool?

public enum CodingKeys: String, CodingKey {
        case autoFitPageToDrawingContent = "AutoFitPageToDrawingContent"
    }

    public init(saveFormat: SaveFormat?, defaultFont: String?, autoFitPageToDrawingContent: Bool?) {
        self.autoFitPageToDrawingContent = autoFitPageToDrawingContent
        super.init(saveFormat: saveFormat, defaultFont: defaultFont)
    }
    
    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(autoFitPageToDrawingContent, forKey: "AutoFitPageToDrawingContent")

        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        autoFitPageToDrawingContent = try container.decodeIfPresent(Bool.self, forKey: "AutoFitPageToDrawingContent")

        try super.init(from: decoder)
    }

}

