//
// DiagramModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DiagramModel: Codable {

    public var fileName: String?
    public var pages: [PageModel]?

public enum CodingKeys: String, CodingKey { 
        case fileName = "FileName"
        case pages = "Pages"
    }

    public init(fileName: String?, pages: [PageModel]?) {
        self.fileName = fileName
        self.pages = pages
    }


}

