//
// EllipseData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class EllipseData: DrawShapeData {

    public override init(pinX: Double, pinY: Double, width: Double, height: Double, shapeStyleData: ShapeStyleData?, text: String?, textStyleData: TextStyleData?) {
        
        super.init(pinX: pinX, pinY: pinY, width: width, height: height, shapeStyleData: shapeStyleData, text: text, textStyleData: textStyleData)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {

        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {

        try super.init(from: decoder)
    }

}

