//
// FileFormatRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FileFormatRequest: Codable {

    public var format: String?

public enum CodingKeys: String, CodingKey { 
        case format = "Format"
    }

    public init(format: String?) {
        self.format = format
    }


}

