//
// ImageSaveOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ImageSaveOptions: RenderingSaveOptions {

    public enum TiffCompression: String, Codable { 
        case RAWNONE_ENUMNONE = "'{raw=None, enum=None}'"
        case RAWRLE_ENUMRLE = "'{raw=Rle, enum=Rle}'"
        case RAWCCITT3_ENUMCCITT3 = "'{raw=Ccitt3, enum=Ccitt3}'"
        case RAWCCITT4_ENUMCCITT4 = "'{raw=Ccitt4, enum=Ccitt4}'"
        case RAWLZW_ENUMLZW = "'{raw=Lzw, enum=Lzw}'"
    }
    public enum ImageColorMode: String, Codable { 
        case RAWNONE_ENUMNONE = "'{raw=None, enum=None}'"
        case RAWGRAYSCALE_ENUMGRAYSCALE = "'{raw=Grayscale, enum=Grayscale}'"
        case RAWBLACK_AND_WHITE_ENUMBLACK_AND_WHITE = "'{raw=BlackAndWhite, enum=BlackAndWhite}'"
    }
    public enum PixelOffsetMode: String, Codable { 
        case RAWDEFAULT_ENUMDEFAULT = "'{raw=Default, enum=Default}'"
        case RAWHIGH_SPEED_ENUMHIGH_SPEED = "'{raw=HighSpeed, enum=HighSpeed}'"
        case RAWHIGH_QUALITY_ENUMHIGH_QUALITY = "'{raw=HighQuality, enum=HighQuality}'"
        case RAWNONE_ENUMNONE = "'{raw=None, enum=None}'"
        case RAWHALF_ENUMHALF = "'{raw=Half, enum=Half}'"
        case RAWINVALID_ENUMINVALID = "'{raw=Invalid, enum=Invalid}'"
    }
    public enum SmoothingMode: String, Codable { 
        case RAWDEFAULT_ENUMDEFAULT = "'{raw=Default, enum=Default}'"
        case RAWHIGH_SPEED_ENUMHIGH_SPEED = "'{raw=HighSpeed, enum=HighSpeed}'"
        case RAWHIGH_QUALITY_ENUMHIGH_QUALITY = "'{raw=HighQuality, enum=HighQuality}'"
        case RAWNONE_ENUMNONE = "'{raw=None, enum=None}'"
        case RAWANTI_ALIAS_ENUMANTI_ALIAS = "'{raw=AntiAlias, enum=AntiAlias}'"
        case RAWINVALID_ENUMINVALID = "'{raw=Invalid, enum=Invalid}'"
    }
    public enum CompositingQuality: String, Codable { 
        case RAWDEFAULT_ENUMDEFAULT = "'{raw=Default, enum=Default}'"
        case RAWHIGH_SPEED_ENUMHIGH_SPEED = "'{raw=HighSpeed, enum=HighSpeed}'"
        case RAWHIGH_QUALITY_ENUMHIGH_QUALITY = "'{raw=HighQuality, enum=HighQuality}'"
        case RAWGAMMA_CORRECTED_ENUMGAMMA_CORRECTED = "'{raw=GammaCorrected, enum=GammaCorrected}'"
        case RAWASSUME_LINEAR_ENUMASSUME_LINEAR = "'{raw=AssumeLinear, enum=AssumeLinear}'"
        case RAWINVALID_ENUMINVALID = "'{raw=Invalid, enum=Invalid}'"
    }
    public enum InterpolationMode: String, Codable { 
        case RAWDEFAULT_ENUMDEFAULT = "'{raw=Default, enum=Default}'"
        case RAWLOW_ENUMLOW = "'{raw=Low, enum=Low}'"
        case RAWHIGH_ENUMHIGH = "'{raw=High, enum=High}'"
        case RAWBILINEAR_ENUMBILINEAR = "'{raw=Bilinear, enum=Bilinear}'"
        case RAWBICUBIC_ENUMBICUBIC = "'{raw=Bicubic, enum=Bicubic}'"
        case RAWNEAREST_NEIGHBOR_ENUMNEAREST_NEIGHBOR = "'{raw=NearestNeighbor, enum=NearestNeighbor}'"
        case RAWHIGH_QUALITY_BILINEAR_ENUMHIGH_QUALITY_BILINEAR = "'{raw=HighQualityBilinear, enum=HighQualityBilinear}'"
        case RAWHIGH_QUALITY_BICUBIC_ENUMHIGH_QUALITY_BICUBIC = "'{raw=HighQualityBicubic, enum=HighQualityBicubic}'"
        case RAWINVALID_ENUMINVALID = "'{raw=Invalid, enum=Invalid}'"
    }

    public var imageBrightness: Double?
    public var imageContrast: Double?
    public var jpegQuality: Int32?
    public var pageCount: Int32?
    public var resolution: Double?
    public var scale: Double?
    public var tiffCompression: TiffCompression?
    public var exportHiddenPage: Bool?
    public var imageColorMode: ImageColorMode?
    public var pageIndex: Int32?
    public var saveForegroundPagesOnly: Bool?
    public var sameAsPdfConversionArea: Bool?
    public var pixelOffsetMode: PixelOffsetMode?
    public var smoothingMode: SmoothingMode?
    public var compositingQuality: CompositingQuality?
    public var interpolationMode: InterpolationMode?

public enum CodingKeys: String, CodingKey {
        case imageBrightness = "ImageBrightness"
        case imageContrast = "ImageContrast"
        case jpegQuality = "JpegQuality"
        case pageCount = "PageCount"
        case resolution = "Resolution"
        case scale = "Scale"
        case tiffCompression = "TiffCompression"
        case exportHiddenPage = "ExportHiddenPage"
        case imageColorMode = "ImageColorMode"
        case pageIndex = "PageIndex"
        case saveForegroundPagesOnly = "SaveForegroundPagesOnly"
        case sameAsPdfConversionArea = "SameAsPdfConversionArea"
        case pixelOffsetMode = "PixelOffsetMode"
        case smoothingMode = "SmoothingMode"
        case compositingQuality = "CompositingQuality"
        case interpolationMode = "InterpolationMode"
    }

    public init(saveFormat: SaveFormat?, defaultFont: String?, area: RectangleF?, exportGuideShapes: Bool?, pageSize: PageSize?, isExportComments: Bool?, imageBrightness: Double?, imageContrast: Double?, jpegQuality: Int32?, pageCount: Int32?, resolution: Double?, scale: Double?, tiffCompression: TiffCompression?, exportHiddenPage: Bool?, imageColorMode: ImageColorMode?, pageIndex: Int32?, saveForegroundPagesOnly: Bool?, sameAsPdfConversionArea: Bool?, pixelOffsetMode: PixelOffsetMode?, smoothingMode: SmoothingMode?, compositingQuality: CompositingQuality?, interpolationMode: InterpolationMode?) {
        self.imageBrightness = imageBrightness
        self.imageContrast = imageContrast
        self.jpegQuality = jpegQuality
        self.pageCount = pageCount
        self.resolution = resolution
        self.scale = scale
        self.tiffCompression = tiffCompression
        self.exportHiddenPage = exportHiddenPage
        self.imageColorMode = imageColorMode
        self.pageIndex = pageIndex
        self.saveForegroundPagesOnly = saveForegroundPagesOnly
        self.sameAsPdfConversionArea = sameAsPdfConversionArea
        self.pixelOffsetMode = pixelOffsetMode
        self.smoothingMode = smoothingMode
        self.compositingQuality = compositingQuality
        self.interpolationMode = interpolationMode
        super.init(saveFormat: saveFormat, defaultFont: defaultFont, area: area, exportGuideShapes: exportGuideShapes, pageSize: pageSize, isExportComments: isExportComments)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(imageBrightness, forKey: "ImageBrightness")
        try container.encodeIfPresent(imageContrast, forKey: "ImageContrast")
        try container.encodeIfPresent(jpegQuality, forKey: "JpegQuality")
        try container.encodeIfPresent(pageCount, forKey: "PageCount")
        
        try container.encodeIfPresent(resolution, forKey: "Resolution")
        try container.encodeIfPresent(scale, forKey: "Scale")
        try container.encodeIfPresent(tiffCompression, forKey: "TiffCompression")
        try container.encodeIfPresent(exportHiddenPage, forKey: "ExportHiddenPage")
        
        try container.encodeIfPresent(imageColorMode, forKey: "ImageColorMode")
        try container.encodeIfPresent(pageIndex, forKey: "PageIndex")
        try container.encodeIfPresent(saveForegroundPagesOnly, forKey: "SaveForegroundPagesOnly")
        try container.encodeIfPresent(sameAsPdfConversionArea, forKey: "SameAsPdfConversionArea")
        
        try container.encodeIfPresent(pixelOffsetMode, forKey: "PixelOffsetMode")
        try container.encodeIfPresent(smoothingMode, forKey: "SmoothingMode")
        try container.encodeIfPresent(compositingQuality, forKey: "CompositingQuality")
        try container.encodeIfPresent(interpolationMode, forKey: "InterpolationMode")
        try super.encode(to: encoder)
    }

    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        imageBrightness = try container.decodeIfPresent(Double.self, forKey: "ImageBrightness")
        imageContrast = try container.decodeIfPresent(Double.self, forKey: "ImageContrast")
        jpegQuality = try container.decodeIfPresent(Int32.self, forKey: "JpegQuality")
        pageCount = try container.decodeIfPresent(Int32.self, forKey: "PageCount")
        
        resolution = try container.decodeIfPresent(Double.self, forKey: "Resolution")
        scale = try container.decodeIfPresent(Double.self, forKey: "Scale")
        tiffCompression = try container.decodeIfPresent(TiffCompression.self, forKey: "TiffCompression")
        exportHiddenPage = try container.decodeIfPresent(Bool.self, forKey: "ExportHiddenPage")
        
        imageColorMode = try container.decodeIfPresent(ImageColorMode.self, forKey: "ImageColorMode")
        pageIndex = try container.decodeIfPresent(Int32.self, forKey: "PageIndex")
        saveForegroundPagesOnly = try container.decodeIfPresent(Bool.self, forKey: "SaveForegroundPagesOnly")
        sameAsPdfConversionArea = try container.decodeIfPresent(Bool.self, forKey: "SameAsPdfConversionArea")
        
        pixelOffsetMode = try container.decodeIfPresent(PixelOffsetMode.self, forKey: "PixelOffsetMode")
        smoothingMode = try container.decodeIfPresent(SmoothingMode.self, forKey: "SmoothingMode")
        compositingQuality = try container.decodeIfPresent(CompositingQuality.self, forKey: "CompositingQuality")
        interpolationMode = try container.decodeIfPresent(InterpolationMode.self, forKey: "InterpolationMode")
        try super.init(from: decoder)
    }

}
