//
// ModifyResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModifyResponse: Codable {

    public var isSuccess: Bool
    public var message: String?

public enum CodingKeys: String, CodingKey { 
        case isSuccess = "IsSuccess"
        case message = "Message"
    }

    public init(isSuccess: Bool, message: String?) {
        self.isSuccess = isSuccess
        self.message = message
    }


}

