//
// PageSize.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PageSize: Codable {

    public enum PaperSizeFormat: String, Codable { 
        case Custom = "Custom"
        case A0 = "A0"
        case A1 = "A1"
        case A2 = "A2"
        case A3 = "A3"
        case A4 = "A4"
        case A5 = "A5"
        case A6 = "A6"
        case A7 = "A7"
        case B0 = "B0"
        case B1 = "B1"
        case B2 = "B2"
        case B3 = "B3"
        case B4 = "B4"
        case B5 = "B5"
        case B6 = "B6"
        case B7 = "B7"
        case C0 = "C0"
        case C1 = "C1"
        case C2 = "C2"
        case C3 = "C3"
        case C4 = "C4"
        case C5 = "C5"
        case C6 = "C6"
        case C7 = "C7"
        case Letter = "Letter"
        case Legal = "Legal"
        case Legal13 = "Legal13"
        case Tabloid = "Tabloid"
        case Executive = "Executive"
        case DL = "DL"
        case COM9 = "COM9"
        case COM10 = "COM10"
        case Monarch = "Monarch"
    }
    public var paperSizeFormat: PaperSizeFormat?

public enum CodingKeys: String, CodingKey { 
        case paperSizeFormat = "PaperSizeFormat"
    }

    public init(paperSizeFormat: PaperSizeFormat?) {
        self.paperSizeFormat = paperSizeFormat
    }


}

