//
// PageModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PageModel: Codable {

    public var pageName: String?
    public var sharps: [SharpModel]?

public enum CodingKeys: String, CodingKey { 
        case pageName = "PageName"
        case sharps = "Sharps"
    }

    public init(pageName: String?, sharps: [SharpModel]?) {
        self.pageName = pageName
        self.sharps = sharps
    }


}

