//
// PageSetting.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** page setting info */

public struct PageSetting: Codable {

    /** Page Name */
    public var name: String?
    /** Page Name */
    public var nameU: String?
    /** Page Width */
    public var pageWidth: Double?
    /** Page Height */
    public var pageHeight: Double?

public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case nameU = "NameU"
        case pageWidth = "PageWidth"
        case pageHeight = "PageHeight"
    }

    public init(name: String?, nameU: String?, pageWidth: Double?, pageHeight: Double?) {
        self.name = name
        self.nameU = nameU
        self.pageWidth = pageWidth
        self.pageHeight = pageHeight
    }


}

