//
// PdfDigitalSignatureDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PdfDigitalSignatureDetails: Codable {

    public enum HashAlgorithm: String, Codable { 
        case RAWSHA1_ENUMSHA1 = "'{raw=Sha1, enum=Sha1}'"
        case RAWSHA256_ENUMSHA256 = "'{raw=Sha256, enum=Sha256}'"
        case RAWSHA384_ENUMSHA384 = "'{raw=Sha384, enum=Sha384}'"
        case RAWSHA512_ENUMSHA512 = "'{raw=Sha512, enum=Sha512}'"
        case RAWMD5_ENUMMD5 = "'{raw=Md5, enum=Md5}'"
    }
    public var signatureDate: String?
    public var reason: String?
    public var location: String?
    public var hashAlgorithm: HashAlgorithm?

public enum CodingKeys: String, CodingKey { 
        case signatureDate = "SignatureDate"
        case reason = "Reason"
        case location = "Location"
        case hashAlgorithm = "HashAlgorithm"
    }

    public init(signatureDate: String?, reason: String?, location: String?, hashAlgorithm: HashAlgorithm?) {
        self.signatureDate = signatureDate
        self.reason = reason
        self.location = location
        self.hashAlgorithm = hashAlgorithm
    }


}

