//
// PdfDigitalSignatureDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PdfDigitalSignatureDetails: Codable {

    public enum HashAlgorithm: String, Codable { 
        case Sha1 = "Sha1"
        case Sha256 = "Sha256"
        case Sha384 = "Sha384"
        case Sha512 = "Sha512"
        case Md5 = "Md5"
    }
    public var signatureDate: String?
    public var reason: String?
    public var location: String?
    public var hashAlgorithm: HashAlgorithm?

public enum CodingKeys: String, CodingKey { 
        case signatureDate = "SignatureDate"
        case reason = "Reason"
        case location = "Location"
        case hashAlgorithm = "HashAlgorithm"
    }

    public init(signatureDate: String?, reason: String?, location: String?, hashAlgorithm: HashAlgorithm?) {
        self.signatureDate = signatureDate
        self.reason = reason
        self.location = location
        self.hashAlgorithm = hashAlgorithm
    }


}

