//
// PdfEncryptionDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PdfEncryptionDetails: Codable {

    public enum Permissions: String, Codable { 
        case DisallowAll = "DisallowAll"
        case Printing = "Printing"
        case ModifyContents = "ModifyContents"
        case ContentCopy = "ContentCopy"
        case ModifyAnnotations = "ModifyAnnotations"
        case FillIn = "FillIn"
        case ContentCopyForAccessibility = "ContentCopyForAccessibility"
        case DocumentAssembly = "DocumentAssembly"
        case HighResolutionPrinting = "HighResolutionPrinting"
        case AllowAll = "AllowAll"
    }
    public enum EncryptionAlgorithm: String, Codable { 
        case _40 = "RC4_40"
        case _128 = "RC4_128"
    }
    public var permissions: Permissions?
    public var encryptionAlgorithm: EncryptionAlgorithm?
    public var userPassword: String?
    public var ownerPassword: String?

public enum CodingKeys: String, CodingKey { 
        case permissions = "Permissions"
        case encryptionAlgorithm = "EncryptionAlgorithm"
        case userPassword = "UserPassword"
        case ownerPassword = "OwnerPassword"
    }

    public init(permissions: Permissions?, encryptionAlgorithm: EncryptionAlgorithm?, userPassword: String?, ownerPassword: String?) {
        self.permissions = permissions
        self.encryptionAlgorithm = encryptionAlgorithm
        self.userPassword = userPassword
        self.ownerPassword = ownerPassword
    }


}

