//
// PointF.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PointF: Codable {

    public var isEmpty: Bool
    public var X: Double
    public var Y: Double

public enum CodingKeys: String, CodingKey { 
        case isEmpty = "IsEmpty"
        case X = "X"
        case Y = "Y"
    }

    public init(isEmpty: Bool, X: Double, Y: Double) {
        self.isEmpty = isEmpty
        self.X = X
        self.Y = Y
    }


}

