//
// RectangleF.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RectangleF: Codable {

    public var location: PointF
    public var size: String
    public var X: Double
    public var Y: Double
    public var width: Double
    public var height: Double
    public var _left: Double
    public var top: Double
    public var _right: Double
    public var bottom: Double
    public var isEmpty: Bool

public enum CodingKeys: String, CodingKey { 
        case location = "Location"
        case size = "Size"
        case X = "X"
        case Y = "Y"
        case width = "Width"
        case height = "Height"
        case _left = "Left"
        case top = "Top"
        case _right = "Right"
        case bottom = "Bottom"
        case isEmpty = "IsEmpty"
    }

    public init(location: PointF, size: String, X: Double, Y: Double, width: Double, height: Double, _left: Double, top: Double, _right: Double, bottom: Double, isEmpty: Bool) {
        self.location = location
        self.size = size
        self.X = X
        self.Y = Y
        self.width = width
        self.height = height
        self._left = _left
        self.top = top
        self._right = _right
        self.bottom = bottom
        self.isEmpty = isEmpty
    }


}

