//
// SaveAsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SaveAsResponse: Codable {

    public var sourceFile: String?
    public var savedFile: String?
    public var additionals: [String]?

public enum CodingKeys: String, CodingKey { 
        case sourceFile = "SourceFile"
        case savedFile = "SavedFile"
        case additionals = "Additionals"
    }

    public init(sourceFile: String?, savedFile: String?, additionals: [String]?) {
        self.sourceFile = sourceFile
        self.savedFile = savedFile
        self.additionals = additionals
    }


}

