//
// SaveOptionsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SaveOptionsRequest: Codable {

    public var fileName: String?
    public var folder: String?
    public var saveOptions: SaveOptionsModel?

public enum CodingKeys: String, CodingKey { 
        case fileName = "FileName"
        case folder = "Folder"
        case saveOptions = "SaveOptions"
    }

    public init(fileName: String?, folder: String?, saveOptions: SaveOptionsModel?) {
        self.fileName = fileName
        self.folder = folder
        self.saveOptions = saveOptions
    }


}

