//
// ShapeStyleData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Shape style setting */

public struct ShapeStyleData: Codable {

    /** the background color of shape,like '#000000' */
    public var backGroundColor: String?

public enum CodingKeys: String, CodingKey { 
        case backGroundColor = "BackGroundColor"
    }

    public init(backGroundColor: String?) {
        self.backGroundColor = backGroundColor
    }


}

