//
// ShapeData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ShapeData: Codable {

    public var ID: Int64
    public var pinX: Double
    public var pinY: Double

public enum CodingKeys: String, CodingKey { 
        case ID = "ID"
        case pinX = "PinX"
        case pinY = "PinY"
    }

    public init(ID: Int64, pinX: Double, pinY: Double) {
        self.ID = ID
        self.pinX = pinX
        self.pinY = pinY
    }


}

