//
// SharpModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SharpModel: Codable {

    public var name: String?

public enum CodingKeys: String, CodingKey { 
        case name = "Name"
    }

    public init(name: String?) {
        self.name = name
    }


}

