//
// TextStyleData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Text style */

public struct TextStyleData: Codable {

    public enum Style: String, Codable { 
        case Bold = "Bold"
        case Italic = "Italic"
        case Underline = "Underline"
        case SmallCaps = "SmallCaps"
        case Undefined = "Undefined"
    }
    public var color: String?
    public var style: Style
    public var fontName: String?
    public var fontSize: Double?

public enum CodingKeys: String, CodingKey { 
        case color = "Color"
        case style = "Style"
        case fontName = "FontName"
        case fontSize = "FontSize"
    }

    public init(color: String?, style: Style, fontName: String?, fontSize: Double?) {
        self.color = color
        self.style = style
        self.fontName = fontName
        self.fontSize = fontSize
    }


}

